name: Test PAT Push

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true

jobs:
  test-pat-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug git remote BEFORE
        run: git remote -v

      - name: Set remote URL with PAT
        run: git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      - name: Debug git remote AFTER
        run: git remote -v

      - name: Git Tag and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}
