name: Build, Sign, Zipalign & Release APK

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Find APK Path
        id: apk
        run: |
          APK=$(find $PWD/app/build/outputs/apk/release -name '*.apk' | head -n 1)
          echo "APK_PATH=$APK" >> $GITHUB_OUTPUT

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > my-release-key.keystore

      - name: Add Android build-tools to PATH (for zipalign)
        run: echo "${ANDROID_HOME}/build-tools/$(ls $ANDROID_HOME/build-tools | sort -V | tail -n 1)" >> $GITHUB_PATH

      - name: Zipalign APK
        run: |
          zipalign -v -p 4 "${{ steps.apk.outputs.APK_PATH }}" aligned.apk

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore my-release-key.keystore \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            aligned.apk "${{ secrets.KEY_ALIAS }}"

      - name: Verify APK signature
        run: jarsigner -verify aligned.apk

      - name: Set remote URL with PAT
        run: git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      - name: Git Tag and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          files: aligned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
